#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'

cookbook 'apt'
cookbook 'git'
cookbook 'build-essential'

cookbook 'rbenv', 
    git: 'git://github.com/fnichol/chef-rbenv.git', 
    ref: "v0.7.2"

cookbook 'ruby_build'
cookbook 'nodejs',
    git: 'http://github.com/mdxp/nodejs-cookbook'

cookbook 'erlang'
cookbook 'couchdb',
  git: 'https://github.com/wohali/couchdb-cookbook'
cookbook 'memcached'

cookbook 'nginx'
cookbook 'runit'
cookbook 'unicorn'

cookbook 'redisio'
