#!/usr/bin/env ruby

#$LOAD_PATH.unshift *Dir["#{File.dirname(__FILE__)}/../vendor/**/lib"]

require 'rubygems'
require "json"



payload_file = File.new("#{File.dirname(__FILE__)}/sample_payload")
hash = eval(payload_file.read)

token_file =  File.new("#{File.dirname(__FILE__)}/.token")
token = eval(token_file.read)
puts token

data_json = JSON.generate(hash["data"])
payload_json = JSON.generate(hash["payload"])

exec "curl -X POST -i --data-binary 'data=#{data_json}&payload=#{payload_json}' http://inch-pebbles.dev/webhook?token=#{token}"
