require "bundler"
require "bundler/gem_tasks"
require 'rake'

task :default => :spec
require "rspec/core/rake_task"
desc "Run the specs"
RSpec::Core::RakeTask.new do |t|
  t.rspec_opts = %w(-fs --color)
end
